### ISSUE TITLE
euroc dataset does not run

### ISSUE THREAD

**Issue by BeatScherrer** [CIFASIS/dense-sptam#7]
The euroc dataset provided by the official provider https://projects.asl.ethz.ch/datasets/doku.php?id=kmavvisualinertialdatasets does not run straight away.

After some time investigating the issue I found that no `camera_info` are published and thus no images are provided.

I am trying to add a helper node which listens to the camera images messages and publishes on the `camera_info` topic with the same timestamp since most of the time the camera configuration is constant over time. Maybe an option to set the camera configuration once would be useful.

After all thanks for sharing your well written work.

**Comment by taihup** [comment]
Check the original S-PTAM documentation, there we provide a script to add camera_info messages to the euroc rosbags.

**Comment by BeatScherrer** [comment]
Thanks for your fast answer, even though I checked for something like this I initially did not found it but did now.

**Comment by taihup** [comment]
Great! have a good time @beatScherrer ;)
