### ISSUE TITLE
Error after playing the rosbag file 

### ISSUE THREAD

**Issue by hlezki** [CIFASIS/dense-sptam#8]
Hi, 
I run the dense-ptam in docker container. However, after playing the bag file, I see the following error even if I created "clouds" folder in the ~/.ros directory. 
![dense_sptam_error](https://user-images.githubusercontent.com/57478079/83155315-c891d700-a109-11ea-8695-e7cdfce0a471.png)

**Comment by hlezki** [comment]
I figured it out..

**Comment by YznMur** [comment]
hi @hlezki
I am facing the same problem.
Can you share your solution, plz?
